//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagrama_Experiencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objective
    {
        public int Id { get; set; }
        public string ObjetiveDescription { get; set; }
        public string Innovation { get; set; }
        public string Results { get; set; }
        public string Sustainability { get; set; }
        public int ExperienceId { get; set; }
    
        public virtual Experience IdExperience { get; set; }
    }
}
